# Dockerfile 12/2020
# nllab-julia - basic Julia environment 

FROM julia:1.5.3
MAINTAINER Nadanai Laohakunakorn <nadanai.laohakunakorn@ed.ac.uk>

RUN julia -e 'import Pkg; Pkg.update()' && \
    julia -e 'using Pkg; Pkg.add("DelimitedFiles")' && \
    julia -e 'using Pkg; Pkg.add("DataFrames")' && \
    julia -e 'using Pkg; Pkg.add("CSV")' && \
    julia -e 'using Pkg; Pkg.add("XLSX")' && \
    julia -e 'using Pkg; Pkg.add("Interpolations")' && \
    julia -e 'using Pkg; Pkg.add("Plots")' && \
    julia -e 'using Pkg; Pkg.add("DifferentialEquations")' && \
    julia -e 'using Pkg; Pkg.add("ProgressBars")' && \
    julia -e 'using Pkg; Pkg.add("Statistics")' && \
    julia -e 'using Pkg; Pkg.add("DiffEqFlux")' && \
    julia -e 'using Pkg; Pkg.add("DiffEqParamEstim")' && \
    julia -e 'using Pkg; Pkg.add("BlackBoxOptim")' && \
    julia -e 'using Pkg; Pkg.add("Flux")' && \
    julia -e 'using Pkg; Pkg.add("RecursiveArrayTools")' && \
    julia -e 'using Pkg; Pkg.add("Optim")' && \
    julia -e 'using Pkg; Pkg.add("IJulia")' && \
    julia -e 'using Pkg; Pkg.add("PyCall")' && \
    julia -e 'using Pkg; Pkg.add("PyPlot")' && \
    julia -e 'using Pkg; Pkg.add("Sundials")' && \
    julia -e 'using Pkg; Pkg.precompile()'
